### ISSUE TITLE
adicionar as métricas de login no Prometeus e grafana

### ISSUE THREAD

**Issue by tonnytg** [tonnytg/42_transcendence#26]
Tarefa:
Adicionar a métrica de sucesso quando usuário logar no Promteus e Grafana

**Comment by tonnytg** [comment]
adicionado

```
apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: 'file'
    disableDeletion: false
    editable: true
    options:
      path: /var/lib/grafana/dashboards
```
